#!/usr/bin/env python3

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path
import tomllib


HEADER = """;;; anvil-shell-filter-builtin.el --- rtk-derived filter specs (auto-generated)  -*- lexical-binding: t; -*-
;;
;; AUTO-GENERATED by scripts/sync-rtk-filters.py -- DO NOT EDIT BY HAND.
;; Regenerate with: make sync-toml-filters
;;
;; Source: vendor/rtk-filters/*.toml (verbatim from rtk-ai/rtk).
;; License: Apache-2.0.  See top-level NOTICE.

;;; Code:

(require 'anvil-shell-filter)

;;;###autoload
(defun anvil-shell-filter-builtin-install ()
  "Install all built-in rtk-derived filter specs."
"""

FOOTER = """
  )

;; Auto-install on require unless suppressed.
(unless (bound-and-true-p anvil-shell-filter-builtin-defer-install)
  (anvil-shell-filter-builtin-install))

(provide 'anvil-shell-filter-builtin)
;;; anvil-shell-filter-builtin.el ends here
"""

KEY_MAP = {
    "description": ":description",
    "match_command": ":match-command",
    "strip_ansi": ":strip-ansi",
    "filter_stderr": ":filter-stderr",
    "replace": ":replace",
    "match_output": ":match-output",
    "strip_lines_matching": ":strip-lines-matching",
    "keep_lines_matching": ":keep-lines-matching",
    "truncate_lines_at": ":truncate-lines-at",
    "max_lines": ":max-lines",
    "tail_lines": ":tail-lines",
    "on_empty": ":on-empty",
}

SEQUENCE_KEYS = {
    "replace",
    "match_output",
    "strip_lines_matching",
    "keep_lines_matching",
}


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Sync rtk TOML filter specs into auto-generated Elisp registrations."
    )
    parser.add_argument(
        "--vendor-dir",
        default="vendor/rtk-filters",
        help="Directory containing rtk filter TOML files.",
    )
    parser.add_argument(
        "--output",
        default="anvil-shell-filter-builtin.el",
        help="Output Elisp file path.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write output; exit non-zero if regeneration would change it.",
    )
    return parser.parse_args(argv)


def elisp_symbol(name: str) -> str:
    return name.replace("_", "-")


def elisp_string(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    )
    return f'"{escaped}"'


def elisp_bool(value: bool) -> str:
    return "t" if value else "nil"


def elisp_list(values: list[str]) -> str:
    return "(" + " ".join(values) + ")"


def elisp_cons_list(values: list[tuple[str, str]]) -> str:
    rendered = [
        f"({elisp_string(pattern)} . {elisp_string(replacement)})"
        for pattern, replacement in values
    ]
    return elisp_list(rendered)


def normalize_mapping_items(items: object, *, value_key: str) -> list[tuple[str, str]]:
    if items is None:
        return []
    if not isinstance(items, list):
        raise ValueError(f"expected list for {value_key}")

    normalized: list[tuple[str, str]] = []
    for item in items:
        if not isinstance(item, dict):
            raise ValueError(f"expected table entries for {value_key}")
        pattern = item.get("pattern")
        value = item.get(value_key)
        if not isinstance(pattern, str) or not isinstance(value, str):
            raise ValueError(f"expected string pattern/{value_key}")
        normalized.append((pattern, value))
    return normalized


def normalize_string_list(items: object, *, key: str) -> list[str]:
    if items is None:
        return []
    if not isinstance(items, list) or any(not isinstance(item, str) for item in items):
        raise ValueError(f"expected list of strings for {key}")
    return list(items)


def build_spec(name: str, data: dict[str, object]) -> list[tuple[str, object]]:
    spec: list[tuple[str, object]] = [(":tag", elisp_symbol(name))]
    for key in (
        "description",
        "match_command",
        "strip_ansi",
        "filter_stderr",
        "replace",
        "match_output",
        "strip_lines_matching",
        "keep_lines_matching",
        "truncate_lines_at",
        "max_lines",
        "tail_lines",
        "on_empty",
    ):
        value = data.get(key)
        if value is None:
            continue
        if key in ("strip_ansi", "filter_stderr"):
            if not isinstance(value, bool):
                raise ValueError(f"expected boolean for {key}")
        elif key in ("description", "match_command", "on_empty"):
            if not isinstance(value, str):
                raise ValueError(f"expected string for {key}")
        elif key in ("truncate_lines_at", "max_lines", "tail_lines"):
            if not isinstance(value, int) or isinstance(value, bool):
                raise ValueError(f"expected integer for {key}")
        elif key == "replace":
            value = normalize_mapping_items(value, value_key="replacement")
            if not value:
                continue
        elif key == "match_output":
            value = normalize_mapping_items(value, value_key="message")
            if not value:
                continue
        elif key in ("strip_lines_matching", "keep_lines_matching"):
            value = normalize_string_list(value, key=key)
            if not value:
                continue
        spec.append((KEY_MAP[key], value))
    return spec


def render_value(value: object) -> str:
    if isinstance(value, bool):
        return elisp_bool(value)
    if isinstance(value, int) and not isinstance(value, bool):
        return str(value)
    if isinstance(value, str):
        if value.startswith(":"):
            return value
        return elisp_string(value)
    if isinstance(value, list):
        if not value:
            return "()"
        if isinstance(value[0], tuple):
            return elisp_cons_list(value)  # type: ignore[arg-type]
        return elisp_list([elisp_string(item) for item in value])  # type: ignore[list-item]
    raise TypeError(f"unsupported value type: {type(value)!r}")


def render_spec(spec: list[tuple[str, object]]) -> str:
    parts: list[str] = []
    for key, value in spec:
        if key == ":tag":
            parts.append(f"{key} {value}")
        else:
            parts.append(f"{key} {render_value(value)}")
    return "'(" + " ".join(parts) + ")"


def load_specs(vendor_dir: Path) -> list[list[tuple[str, object]]]:
    specs: list[list[tuple[str, object]]] = []
    for path in sorted(vendor_dir.glob("*.toml")):
        with path.open("rb") as handle:
            data = tomllib.load(handle)
        filters = data.get("filters")
        if not isinstance(filters, dict):
            raise ValueError(f"{path}: missing [filters.<name>] table")
        for name, table in filters.items():
            if not isinstance(name, str) or not isinstance(table, dict):
                raise ValueError(f"{path}: invalid filter table")
            specs.append(build_spec(name, table))
    return sorted(specs, key=lambda spec: str(spec[0][1]))


def generate_elisp(vendor_dir: Path) -> str:
    specs = load_specs(vendor_dir)
    lines = [HEADER]
    for spec in specs:
        lines.append(
            f"  (anvil-shell-filter-register-from-spec {render_spec(spec)})\n"
        )
    lines.append(FOOTER)
    return "".join(lines)


def run(argv: list[str]) -> int:
    args = parse_args(argv)
    vendor_dir = Path(args.vendor_dir)
    output_path = Path(args.output)
    toml_files = sorted(vendor_dir.glob("*.toml"))

    if not toml_files:
        print(
            f"No TOML filter specs found in {vendor_dir}; skipping sync.",
            file=sys.stderr,
        )
        return 0

    rendered = generate_elisp(vendor_dir)

    if args.check:
        existing = output_path.read_text(encoding="utf-8") if output_path.exists() else ""
        if existing == rendered:
            return 0
        print(
            f"{output_path} is out of date; run `make sync-toml-filters`.",
            file=sys.stderr,
        )
        diff = difflib.unified_diff(
            existing.splitlines(),
            rendered.splitlines(),
            fromfile=str(output_path),
            tofile=f"{output_path} (generated)",
            lineterm="",
        )
        for line in diff:
            print(line, file=sys.stderr)
        return 1

    output_path.write_text(rendered, encoding="utf-8")
    return 0


def main() -> None:
    raise SystemExit(run(sys.argv[1:]))


if __name__ == "__main__":
    main()
